#!/usr/bin/python3

"""
Create cities...
"""

from flask import jsonify, abort, request
from models.state import State
from models.city import City
from models import storage
from api.v1.views import app_views


@app_views.rout('/
